config/routes.rb
# Prefix               Verb   URI Pattern                                       Controller#Action
# root                 GET    /                                                 articles#index
# article_comments     GET    /articles/:article_id/comments(.:format)          comments#index
#                      POST   /articles/:article_id/comments(.:format)          comments#create
# new_article_comment  GET    /articles/:article_id/comments/new(.:format)      comments#new
# edit_article_comment GET    /articles/:article_id/comments/:id/edit(.:format) comments#edit
# article_comment      GET    /articles/:article_id/comments/:id(.:format)      comments#show
#                      PATCH  /articles/:article_id/comments/:id(.:format)      comments#update
#                      PUT    /articles/:article_id/comments/:id(.:format)      comments#update
#                      DELETE /articles/:article_id/comments/:id(.:format)      comments#destroy
# articles             GET    /articles(.:format)                               articles#index
#                      POST   /articles(.:format)                               articles#create
# new_article          GET    /articles/new(.:format)                           articles#new
# edit_article         GET    /articles/:id/edit(.:format)                      articles#edit
# article              GET    /articles/:id(.:format)                           articles#show
#                      PATCH  /articles/:id(.:format)                           articles#update
#                      PUT    /articles/:id(.:format)                           articles#update
#                      DELETE /articles/:id(.:format)                           articles#destroy
# tags                 GET    /tags(.:format)                                   tags#index
#                      POST   /tags(.:format)                                   tags#create
# new_tag              GET    /tags/new(.:format)                               tags#new
# edit_tag             GET    /tags/:id/edit(.:format)                          tags#edit
#  tag                 GET    /tags/:id(.:format)                               tags#show
#                      PATCH  /tags/:id(.:format)                               tags#update
#                      PUT    /tags/:id(.:format)                               tags#update
#                      DELETE /tags/:id(.:format)                               tags#destroy
# authors              GET    /authors(.:format)                                authors#index
#                      POST   /authors(.:format)                                authors#create
# new_author           GET    /authors/new(.:format)                            authors#new
# edit_author          GET    /authors/:id/edit(.:format)                       authors#edit
# author               GET    /authors/:id(.:format)                            authors#show
#                      PATCH  /authors/:id(.:format)                            authors#update
#                      PUT    /authors/:id(.:format)                            authors#update
#                      DELETE /authors/:id(.:format)                            authors#destroy
# author_sessions      POST   /author_sessions(.:format)                        author_sessions#create
# new_author_session   GET    /author_sessions/new(.:format)                    author_sessions#new
# author_session       DELETE /author_sessions/:id(.:format)                    author_sessions#destroy
# login                GET    /login(.:format)                                  author_sessions#new
# logout               GET    /logout(.:format)                                 author_sessions#destroy

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

# bundle exec rake routes

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :taggings
    has_many :tags, through: :taggings

    validates :title, presence: true

    has_attached_file :image
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
    
    def tag_list
      tags.join(", ")
    end

    def tag_list=(tags_string)
      tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
      new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
      self.tags = new_or_found_tags
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    include ArticlesHelper
    before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
        
        @comment = Comment.new
        @comment.article_id = @article.id
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.save

        flash.notice = "Article '#{@article.title}' Created!"
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash.notice = "Article '#{@article.title}' Deleted!"

        redirect_to articles_path(@articles)
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        flash.notice = "Article '#{@article.title}' Updated!"
      
        redirect_to article_path(@article)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
    <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
    <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.label :tag_list %><br />
      <%= f.text_field :tag_list %>
    </p>
    <p>
      <% if @article.image.exists? %>
        <%= image_tag @article.image.url %><br/>
      <% end %>
      <%= f.label :image, "Attach a New Image" %><br />
      <%= f.file_field :image %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
    <%= link_to article.title, article_path(article),
        class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p>
  <% if @article.image.exists? %>
    <%= image_tag @article.image.url %>
  <% end %>
</p>

<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>

<% if logged_in? %>
  <%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>
  <%= link_to "edit", edit_article_path(@article) %>
<% end %>